# This is the digit recognition kaggle project!!!

In [62]:
print("Digit recognition")

import tensorflow as tf
import tensorflow.keras as keras
# import tensorflow.nlp as nlp
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
# from tensorflow.nlp.layers import FourierTransformLayer
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.optimizers import SGD

import pandas as pd
import sklearn

import matplotlib.pyplot as plt

plt.style.use("ggplot")
np.random.seed(0)
tf.random.set_seed(0)


Digit recognition


In [2]:
train = pd.read_csv('digit-recognizer/train.csv')
test = pd.read_csv('digit-recognizer/test.csv')

In [6]:
train_X = train.drop('label', axis=1).astype('float32') / 255.0
train_y = train['label']

test_x = test.astype('float32') / 255.0

In [38]:
train_X_np = train_X.to_numpy()
train_X_np = train_X_np.reshape(train_X_np.shape[0], 28, 28, 1)

train_y_np = train_y.to_numpy()

# print(train_X_np.shape)
train_y_np = to_categorical(train_y_np)
print(train_y_np)
# print(train_X.shape)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [69]:
# def define_model():
opt = SGD(learning_rate=0.01, momentum=0.9)

model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

model2 = Sequential()
model2.add(Conv2D(32, (5, 5), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
model2.add(Conv2D(32, (4, 4), activation='relu', kernel_initializer='he_uniform'))
model2.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform'))
model2.add(MaxPooling2D((2, 2)))
model2.add(Flatten())
# model.add(Dropout(0.01))
model2.add(Dense(10, activation='softmax'))
model2.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])


model3 = Sequential()
model3.add(Conv2D(32, (5, 5), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
model3.add(Conv2D(32, (4, 4), activation='relu', kernel_initializer='he_uniform'))
model3.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform'))
model3.add(MaxPooling2D((2, 2)))
model3.add(Flatten())
model3.add(Dropout(0.01))
model3.add(Dense(10, activation='softmax'))
model3.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

# model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
# model.add(Dropout(0.01))
# model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
# compile model
# return model

# model = define_model()

In [58]:
# model.

model.fit(train_X_np, train_y_np)

1313/1313 [==============================] - 14s 10ms/step - loss: 0.2130 - accuracy: 0.9365


In [68]:
model2.fit(train_X_np, train_y_np)

1313/1313 [==============================] - 68s 51ms/step - loss: 0.1370 - accuracy: 0.9571


In [70]:
model3.fit(train_X_np, train_y_np)

1313/1313 [==============================] - 66s 49ms/step - loss: 0.1364 - accuracy: 0.9572
