# This is the digit recognition kaggle project!!!

In [102]:
print("Digit recognition")

import tensorflow as tf
import tensorflow.keras as keras
# import tensorflow.nlp as nlp
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
# from tensorflow.nlp.layers import FourierTransformLayer
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.optimizers import SGD

import pandas as pd
import sklearn
import csv
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
plt.style.use("ggplot")
np.random.seed(0)
tf.random.set_seed(0)


Digit recognition


In [5]:
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [6]:
train_X = train.drop('label', axis=1).astype('float32') / 255.0
train_y = train['label']

test_x = test.astype('float32') / 255.0

In [53]:
test_x_np = test_x.to_numpy()
test_x_np = test_x_np.reshape(test_x_np.shape[0], 28, 28, 1)

In [7]:
train_X_np = train_X.to_numpy()
train_X_np = train_X_np.reshape(train_X_np.shape[0], 28, 28, 1)

train_y_np = train_y.to_numpy()

# print(train_X_np.shape)
train_y_np = to_categorical(train_y_np)
print(train_y_np)
# print(train_X.shape)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [43]:
opt = SGD(learning_rate=0.001, momentum=0.9)

model4 = Sequential()
model4.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
model4.add(MaxPooling2D((2, 2)))
model4.add(Flatten())
model4.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.01))
model4.add(Dense(1000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dense(1000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.03))
model4.add(Dense(1000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.03))
model4.add(Dense(10000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.2))
model4.add(Dense(10000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.07))
model4.add(Dense(10000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.05))
model4.add(Dense(10000, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dropout(0.06))
# model4.add(Conv2D(100, (3, 3), activation='relu', kernel_initializer='he_uniform'))
model4.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
model4.add(Dense(10, activation='softmax'))
model4.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])



In [46]:
# model.

model4.fit(train_X_np, train_y_np,epochs=20, batch_size=32)


Epoch 1/20
1313/1313 [==============================] - 800s 609ms/step - loss: 0.0786 - accuracy: 0.9755
Epoch 2/20
1313/1313 [==============================] - 808s 615ms/step - loss: 0.0599 - accuracy: 0.9808
Epoch 3/20
1313/1313 [==============================] - 801s 610ms/step - loss: 0.0457 - accuracy: 0.9853
Epoch 4/20
1313/1313 [==============================] - 804s 612ms/step - loss: 0.0358 - accuracy: 0.9886
Epoch 5/20
1313/1313 [==============================] - 802s 611ms/step - loss: 0.0267 - accuracy: 0.9910
Epoch 6/20
1313/1313 [==============================] - 788s 600ms/step - loss: 0.0201 - accuracy: 0.9935
Epoch 7/20
1313/1313 [==============================] - 762s 580ms/step - loss: 0.0190 - accuracy: 0.9934
Epoch 8/20
1313/1313 [==============================] - 759s 578ms/step - loss: 0.0149 - accuracy: 0.9950
Epoch 9/20
1313/1313 [==============================] - 757s 577ms/step - loss: 0.0102 - accuracy: 0.9969
Epoch 10/20
1313/1313 [=======================

In [101]:
model4.summary()

Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_70 (Conv2D)          (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_23 (MaxPooli  (None, 13, 13, 32)        0         
 ng2D)                                                           
                                                                 
 flatten_23 (Flatten)        (None, 5408)              0         
                                                                 
 dense_70 (Dense)            (None, 100)               540900    
                                                                 
 dropout_47 (Dropout)        (None, 100)               0         
                                                                 
 dense_71 (Dense)            (None, 1000)              101000    
                                                     

In [55]:
#Make predictions on the test data
test_y = model4.predict(
    test_x_np,
    batch_size=None,
    verbose='auto',
    steps=None,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False
)

875/875 [==============================] - 79s 91ms/step


In [99]:
#Find the index with the largest value
#28000 images in test data
resultArr = np.ones((28000,2))
for i in range(28000):
    resultArr[i][0] = i+1
    resultArr[i][1] = int(np.argmax(test_y[i]))
resultArr = resultArr.astype('int')
for i in range(10):
    print(resultArr[i])


[1 2]
[2 0]
[3 9]
[4 0]
[5 3]
[6 9]
[7 0]
[8 3]
[9 0]
[10  3]


In [98]:
df = pd.DataFrame(resultArr)
df.to_csv("./submission.csv", header=False, index=False)